/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppNewRouteImport } from './routes/app.new'
import { Route as AuthVerifyRouteImport } from './routes/_auth.verify'
import { Route as AuthSignUpRouteImport } from './routes/_auth.sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth.sign-in'
import { Route as AuthSetupWorkspaceRouteImport } from './routes/_auth.setup-workspace'
import { Route as AuthInviteRouteImport } from './routes/_auth.invite'
import { Route as AppDocsIndexRouteImport } from './routes/app.docs.index'
import { Route as AppSitesSiteIdRouteImport } from './routes/app.sites.$siteId'
import { Route as AppDocsNewRouteImport } from './routes/app.docs.new'
import { Route as AppDocsDocIdRouteImport } from './routes/app.docs.$docId'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppNewRoute = AppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSetupWorkspaceRoute = AuthSetupWorkspaceRouteImport.update({
  id: '/setup-workspace',
  path: '/setup-workspace',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInviteRoute = AuthInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AuthRoute,
} as any)
const AppDocsIndexRoute = AppDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => AppRoute,
} as any)
const AppSitesSiteIdRoute = AppSitesSiteIdRouteImport.update({
  id: '/sites/$siteId',
  path: '/sites/$siteId',
  getParentRoute: () => AppRoute,
} as any)
const AppDocsNewRoute = AppDocsNewRouteImport.update({
  id: '/docs/new',
  path: '/docs/new',
  getParentRoute: () => AppRoute,
} as any)
const AppDocsDocIdRoute = AppDocsDocIdRouteImport.update({
  id: '/docs/$docId',
  path: '/docs/$docId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/invite': typeof AuthInviteRoute
  '/setup-workspace': typeof AuthSetupWorkspaceRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/verify': typeof AuthVerifyRoute
  '/app/new': typeof AppNewRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/docs/$docId': typeof AppDocsDocIdRoute
  '/app/docs/new': typeof AppDocsNewRoute
  '/app/sites/$siteId': typeof AppSitesSiteIdRoute
  '/app/docs/': typeof AppDocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invite': typeof AuthInviteRoute
  '/setup-workspace': typeof AuthSetupWorkspaceRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/verify': typeof AuthVerifyRoute
  '/app/new': typeof AppNewRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/docs/$docId': typeof AppDocsDocIdRoute
  '/app/docs/new': typeof AppDocsNewRoute
  '/app/sites/$siteId': typeof AppSitesSiteIdRoute
  '/app/docs': typeof AppDocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/_auth/invite': typeof AuthInviteRoute
  '/_auth/setup-workspace': typeof AuthSetupWorkspaceRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_auth/verify': typeof AuthVerifyRoute
  '/app/new': typeof AppNewRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/docs/$docId': typeof AppDocsDocIdRoute
  '/app/docs/new': typeof AppDocsNewRoute
  '/app/sites/$siteId': typeof AppSitesSiteIdRoute
  '/app/docs/': typeof AppDocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/invite'
    | '/setup-workspace'
    | '/sign-in'
    | '/sign-up'
    | '/verify'
    | '/app/new'
    | '/app/settings'
    | '/app/'
    | '/app/docs/$docId'
    | '/app/docs/new'
    | '/app/sites/$siteId'
    | '/app/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invite'
    | '/setup-workspace'
    | '/sign-in'
    | '/sign-up'
    | '/verify'
    | '/app/new'
    | '/app/settings'
    | '/app'
    | '/app/docs/$docId'
    | '/app/docs/new'
    | '/app/sites/$siteId'
    | '/app/docs'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/app'
    | '/_auth/invite'
    | '/_auth/setup-workspace'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_auth/verify'
    | '/app/new'
    | '/app/settings'
    | '/app/'
    | '/app/docs/$docId'
    | '/app/docs/new'
    | '/app/sites/$siteId'
    | '/app/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/new': {
      id: '/app/new'
      path: '/new'
      fullPath: '/app/new'
      preLoaderRoute: typeof AppNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/verify': {
      id: '/_auth/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/setup-workspace': {
      id: '/_auth/setup-workspace'
      path: '/setup-workspace'
      fullPath: '/setup-workspace'
      preLoaderRoute: typeof AuthSetupWorkspaceRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/invite': {
      id: '/_auth/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof AuthInviteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/app/docs/': {
      id: '/app/docs/'
      path: '/docs'
      fullPath: '/app/docs/'
      preLoaderRoute: typeof AppDocsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sites/$siteId': {
      id: '/app/sites/$siteId'
      path: '/sites/$siteId'
      fullPath: '/app/sites/$siteId'
      preLoaderRoute: typeof AppSitesSiteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/docs/new': {
      id: '/app/docs/new'
      path: '/docs/new'
      fullPath: '/app/docs/new'
      preLoaderRoute: typeof AppDocsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/docs/$docId': {
      id: '/app/docs/$docId'
      path: '/docs/$docId'
      fullPath: '/app/docs/$docId'
      preLoaderRoute: typeof AppDocsDocIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AuthRouteChildren {
  AuthInviteRoute: typeof AuthInviteRoute
  AuthSetupWorkspaceRoute: typeof AuthSetupWorkspaceRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthInviteRoute: AuthInviteRoute,
  AuthSetupWorkspaceRoute: AuthSetupWorkspaceRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AppRouteChildren {
  AppNewRoute: typeof AppNewRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDocsDocIdRoute: typeof AppDocsDocIdRoute
  AppDocsNewRoute: typeof AppDocsNewRoute
  AppSitesSiteIdRoute: typeof AppSitesSiteIdRoute
  AppDocsIndexRoute: typeof AppDocsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppNewRoute: AppNewRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppDocsDocIdRoute: AppDocsDocIdRoute,
  AppDocsNewRoute: AppDocsNewRoute,
  AppSitesSiteIdRoute: AppSitesSiteIdRoute,
  AppDocsIndexRoute: AppDocsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
